### ISSUE TITLE
n번 시행시 전략 vs 랜덤 확률 계산 함수 만들기

### ISSUE THREAD

**Issue by tjsgh531** [3lee1jeon/31_100_people#2]
## Description

전략 없을 때 n번을 실행하면 몇 번 살아남는지,
전략 있을 때 n번 실행하면 몇 번 살아남는지를 카운트 하여 확률을 계산

파라미터로 n을 받음

- 랜덤 박스 제작 함수
- 전략 유무의 방식으로 했을 경우 사는지 죽는지 결과 반환 함수
둘은 이미 구현됐다고 취급

## Tasks

- [x] 전략 없을 때 n번을 실행하면 사는 횟수를 카운트 합니다.
- [x] 전략 있을 때 n 번을 실행하면 사는 횟수를 카운트 합니다.
- [x] 두 전략의 확률을 계산하여 반환 합니다

##Reference
