### ISSUE TITLE
죄수 100명이 무작위로 상자 선택

### ISSUE THREAD

**Issue by jylee9018** [3lee1jeon/31_100_people#3]
## Description
죄수 1명(1명~100명)이 무작위로 상자를 선택하여 그 상자에 자신의 번호가 있다면 성공, 아니면 실패
(총 50회 선택 가능)
 
## Tasks
- [x] 무작위로 번호가 담긴 상자(리스트) 받기 
- [x] 죄수는 최대 50회까지 상자 안 번호와 자신의 번호가 일치하는지 확인. 일치하면 성공(T), 아니면 실패(F)
- [x] 결과값은 성공(T), 실패(F)
